# Nome do seu fluxo de trabalho
name: Deploy to GitHub Pages

# Este workflow roda toda vez que você faz um push para a branch 'main'
on:
  push:
    branches:
      - main  # ou 'master', dependendo do nome da sua branch principal

# Permissões necessárias para o workflow
permissions:
  contents: read
  pages: write
  id-token: write

# Tarefas (jobs) que o workflow irá executar
jobs:
  # Tarefa de build e deploy
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Baixa o código do seu repositório
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Configura o GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 3. Constroi o "artefato" (os arquivos do site) a partir da sua pasta
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # AQUI ESTÁ A MÁGICA:
          # Especifique o caminho para a pasta que contém seu site
          path: './src/main/resources/static'

      # 4. Faz o deploy no GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4